#!php
<?php

// A util to create a user hash

require 'BasicAuth.php';

$basic = new BasicAuth('../../users.ini');

// If there weren't enough arguments, show the syntax
if (empty($argv[1]) || empty($argv[2]) ) {
    die("Syntax: userhash [username] [password]\n");
}

$user = $argv[1];
$pass = $argv[2];
echo $user . '=' . $basic->hash($pass) . "\n";
